;; to fix emacs 24's dropping of 'make-local-hook
(defalias 'make-local-hook
  (if (featurep 'xemacs)
      'make-local-hook
    'identity))


(add-to-list 'load-path "~/.emacs.d/vendor")
(add-to-list 'load-path "~/.emacs.d/vendor/auctex")
(add-to-list 'load-path "~/.emacs.d/vendor/reftex/lisp")
(add-to-list 'load-path "~/.emacs.d/vendor/sml-mode")
(add-to-list 'load-path "~/.emacs.d/vendor/auto-complete")
(add-to-list 'load-path "~/.emacs.d/vendor/auto-complete-clang")
(add-to-list 'load-path "~/.emacs.d/vendor/popup")

(setq custom-file "~/.emacs.d/lisp/ktangwon/custom.el")
(load custom-file 'noerror)

(load "ktangwon/env")
(load "ktangwon/global")
(load "ktangwon/defuns")
(load "sml-mode")
(load "ktangwon/sml")
(load "auctex.el" nil t t)
(load "ktangwon/auctex")
(load "ktangwon/reftex")
(load "ktangwon/bindings")
(load "ktangwon/tabs")
(load "ktangwon/disabled")
(load "ktangwon/fonts")
(load "ktangwon/utf-8")
(load "ktangwon/scratch")
(load "ktangwon/color-theme")
(load "ktangwon/grep")
(load "ktangwon/diff")
(load "ktangwon/ido")
(load "ktangwon/dired")
(load "ktangwon/recentf")
(load "ktangwon/uniquify")
(load "ktangwon/rectangle")
(load "ktangwon/org")
(load "ktangwon/zoom")
(load "ktangwon/flymake")
(load "ktangwon/javascript")
(load "ktangwon/ri-emacs")
(load "ktangwon/gnuplot-mode")
(load "ktangwon/mac")
(load "ktangwon/server-mode")
(load "ktangwon/shell-mode")
(load "ktangwon/powerline-mode")
(load "ktangwon/auto-complete-clang")
(load "ktangwon/private" 'noerror)

;; (load "ktangwon/hl-line")
;; (load "ktangwon/iswitchb")
(vendor 'color-theme)
(vendor 'ruby-mode)
(vendor 'gnuplot)
(vendor 'rinari)
(vendor 'textmate)
(vendor 'maxframe)
;; (vendor 'sml-mode 'sml-mode-startup)
(vendor 'tree-mode)
(vendor 'windata)
(vendor 'dirtree)
(vendor 'filladapt)
(vendor 'coffee-mode)
(vendor 'haml-mode)
(vendor 'sass-mode)
(vendor 'htmlize)
(vendor 'full-ack      'ack 'ack-same 'ack-find-same-file 'ack-find-file 'ack-interactive)
;; (vendor 'cdargs        'cv 'cdargs)
(vendor 'magit         'magit-status)
(vendor 'scala-mode2)
(vendor 'psvn          'svn-status)
(vendor 'js2-mode      'js2-mode)
(vendor 'markdown-mode 'markdown-mode)
;; (vendor 'textile-mode  'textile-mode)
(vendor 'csv-mode      'csv-mode)
(vendor 'yaml-mode     'yaml-mode)
(vendor 'inf-ruby      'inf-ruby)
(vendor 'rcodetools    'xmp)
(vendor 'yasnippet)
;; (vendor 'projectile)
(vendor 'cl-lib)
(vendor 'powerline)
(vendor 'popup)
(vendor 'auto-complete)
(vendor 'auto-complete-clang)
;; (vendor 'jekyll)
(vendor 'lua-mode      'lua-mode)
(vendor 'feature-mode)
(vendor 'mode-line-bell)
(vendor 'revbufs       'revbufs)
(vendor 'go-mode)
;; (vendor 'auctex)
;; (vendor 'auctex        'tex-site)
;; (vendor 'ruby-electric 'ruby-electric-mode)
;;

(add-to-list 'load-path (expand-file-name "~/.emacs.d/vendor"))

;; temp place for emacs-for-python; will clean up later
(add-to-list 'load-path "~/.emacs.d/vendor/emacs-for-python/")
(require 'epy-setup)      ;; It will setup other loads, it is required!
(require 'epy-python)     ;; If you want the python facilities [optional]
(require 'epy-completion) ;; If you want the autocompletion settings [optional]
